build:
  # assets:
  #   image: node:6
  #   commands:
  #       - npm install
  #       - npm run build
  # test:
  #   image: apihackers/wagtail:1.5
  #   commands:
  #     - pip install pytest pytest-django
      # - py.test
  package:
    image: apihackers/wagtail:1.5
    commands:
      - pip install -e . wheel
      - ./manage.py compilemessages
      - python3 setup.py egg_info -b $DRONE_BUILD_NUMBER bdist_wheel
  flake8:
    image: python:3.5-alpine
    commands:
      - pip install flake8
      - flake8 wapps

publish:
  devpi:
    server: https://pypi.noirbizarre.info/
    index: apihackers/sublime
    username: $$DEVPI_USER
    password: $$DEVPI_PASSWORD

compose:
  database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=wapps
      - POSTGRES_PASSWORD=wapps
