build:
  flake8:
    image: apihackers/flake8
    commands:
      - flake8 wapps

  # assets:
  #   image: node:6
  #   commands:
  #     - npm install
  #     - npm run build

  package:
    environment:
      PY_INDEX: $$DEVPI_SERVER$$DEVPI_INDEX/
      DJANGO_SETTINGS: drone_settings
      EGG_TAG: $$BUILD_NUMBER+$$BRANCH
    image: apihackers/wagtail:1.5
    commands:
      # Make installed packages cacheable
      - export PYTHONUSERBASE=$DRONE_DIR/py-user-base
      - export PATH=$DRONE_DIR/py-user-base/bin:$PATH
      # Install, build and package
      - pip3 install --user -i $PY_INDEX -e . wheel invoke Babel
      - inv dist -b ${EGG_TAG%%+master}

publish:
  devpi:
    image: apihackers/drone-devpi
    server: $$DEVPI_SERVER
    index: $$DEVPI_INDEX
    username: $$DEVPI_USER
    password: $$DEVPI_PASSWORD
    files:
      - dist/wapps-*.whl

cache:
  mount:
    - node_modules
    - py-user-base

compose:
  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=wapps
      - POSTGRES_PASSWORD=wapps
