variables:
  DJANGO_SETTINGS: drone_settings
  EGG_TAG: $CI_JOB_ID+$CI_COMMIT_REF_SLUG

stages:
- lint
- build
- test
- release

flake8:
  stage: lint
  image:
    name: apihackers/flake8
    entrypoint: ["/bin/sh", "-c"]
  script:
    - flake8 wapps

package:
  stage: build
  image: apihackers/wagtail:1.12
  script:
    # Install, build and package
    - pip install -r requirements/develop
    - inv test
    - inv dist -b ${EGG_TAG%%+master}
